from django.urls import path

from .views import (
    health_view,
    admin_only_view,
    admin_permissions_view,
    admin_summary_view,
    admin_user_detail_view,
    admin_user_role_view,
    admin_user_status_view,
    admin_users_view,
    appointment_status_view,
    appointment_reschedule_view,
    chatbot_reply_view,
    chatbot_status_view,
    chat_conversations_view,
    chat_messages_view,
    emotional_records_view,
    emotional_trend_view,
    appointments_view,
    login_view,
    me_view,
    profile_view,
    professional_agenda_politicas_view,
    professional_date_availability_view,
    professional_exception_day_view,
    professional_next_slots_view,
    professional_schedule_view,
    professional_slots_view,
    professionals_view,
    questionnaires_initial_view,
    register_view,
)

urlpatterns = [
    path("health/", health_view, name="health"),
    path("auth/register/", register_view, name="auth-register"),
    path("auth/login/", login_view, name="auth-login"),
    path("auth/me/", me_view, name="auth-me"),
    path("auth/profile/", profile_view, name="auth-profile"),
    path("auth/admin-only/", admin_only_view, name="auth-admin-only"),
    path("admin/resumen/", admin_summary_view, name="admin-summary"),
    path("admin/usuarios/", admin_users_view, name="admin-users"),
    path("admin/usuarios/<int:user_id>/", admin_user_detail_view, name="admin-user-detail"),
    path("admin/usuarios/<int:user_id>/rol/", admin_user_role_view, name="admin-user-role"),
    path("admin/usuarios/<int:user_id>/estado/", admin_user_status_view, name="admin-user-status"),
    path("admin/usuarios/<int:user_id>/permisos/", admin_permissions_view, name="admin-user-permissions"),
    path("profesionales/", professionals_view, name="professionals-list"),
    path("profesionales/<int:profesional_id>/slots/", professional_slots_view, name="professional-slots"),
    path("profesionales/<int:profesional_id>/slots/proximos/", professional_next_slots_view, name="professional-next-slots"),
    path("profesionales/mi/agenda/", professional_schedule_view, name="professional-schedule"),
    path("profesionales/mi/agenda-politicas/", professional_agenda_politicas_view, name="professional-agenda-politicas"),
    path("profesionales/mi/excepcion-dia/", professional_exception_day_view, name="professional-exception-day"),
    path("profesionales/mi/disponibilidad-fecha/", professional_date_availability_view, name="professional-date-availability"),
    path("citas/", appointments_view, name="appointments"),
    path("citas/<int:appointment_id>/estado/", appointment_status_view, name="appointment-status"),
    path("citas/<int:appointment_id>/reprogramar/", appointment_reschedule_view, name="appointment-reschedule"),
    path("emociones/", emotional_records_view, name="emotional-records"),
    path("emociones/tendencia/", emotional_trend_view, name="emotional-trend"),
    path("cuestionarios/inicial/", questionnaires_initial_view, name="questionnaire-initial"),
    path("chat/conversaciones/", chat_conversations_view, name="chat-conversations"),
    path("chat/conversaciones/<int:conversation_id>/mensajes/", chat_messages_view, name="chat-messages"),
    path("chatbot/reply/", chatbot_reply_view, name="chatbot-reply"),
    path("chatbot/estado/", chatbot_status_view, name="chatbot-status"),
]
